- name: advanced loops
  hosts: mysql
  become: yes

  tasks:
   - name: advanced loop
     ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"

     loop:
     - {name: 'maven' , state: 'installed'}
     - {name: 'postfix' , state: 'absent'}

     

     