- name : check user exist or not 
  hosts: mysql

  tasks:
   - name: check user roboshop exist or not 
     ansible.builtin.command: id roboshop
     register: srikar 
     ignore_errors: true

   - name: print the output 
     ansible.builtin.debug:
      msg: "output is {{srikar}}"

   - name: print the exit status
     ansible.builtin.debug:
      msg: "output is {{srikar.rc}}"

   - name: create the user 
     become: yes
     ansible.builtin.user:
      name: roboshop
     when: srikar.rc != 0