- name: install nginx
  hosts: mysql
  become: yes

  tasks:
  - name: install nginx
    ansible.builtin.yum:
    name: nginx
    state: installed
  
  tasks:
  - name: start nginx
    ansible.builtin.service:
    name: nginx
    state: started

