- name: variables precedency 
  hosts: mysql
  vars:
   FAV_PLAYER= Kohli-play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false 
  tasks:
  - name: print the task level
    vars:
     FAV_PLAYER= Kohli-task
    ansible.buitlin.debug:
     msg: "the fav player is {{FAV_PLAYER}}"