- name: variables precedency 
  hosts: mysql
  vars:
   FAV_PLAYER: Kohli-play
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: FAV_PLAYER
  #   prompt: please enter your FAV_PLAYER
  #   private: false 
  # tasks:
  # - name: print the task level
   
  #   ansible.builtin.debug:
  #    msg: "the fav player is: {{FAV_PLAYER}}"