- name: variables from files
  hosts: localhost
  vars_files:
  - variables.yml
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: "The {{TOUR}}, starts today and eagerly waiting to see my {{FAV_PLAYER}} hitting the {{ACHIEVEMENT}}"