- name: variables from files
  hosts: localhost

  vars_files:
  - variables1.yml

  tasks:
   - name: srikar varma
    ansible.builtin.debug:
     msg: "The {{TOURNAMENT}}, starts today and eagerly waiting to see my {{FAV_PLAYER}} hitting {{ACHIEVEMENT}}"